# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', '/designfiles/', 'README.md', 'LICENSE.txt', 'CNAME', vendor]


# Site Settings
title: "Kerala Microsoft Users Group"
email: "info@k-mug.net"
description: "K-MUG is one of the most successful technical communities in India, which focus on Microsoft Technologies."
baseurl: ""
url: "https://k-mug.net"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-84710058-1"
googleAnalyticsSiteUrl: "k-mug.net"
siteVerification: "-wVmxk-eyHhW7d58D7an95_njBOYrbVy0HVI8cJPdtg"

# Organizer Info
organizerName: "Kerala Microsoft Users Group"
organizerAlternateName: "K-MUG"
organizerDescription: "K-MUG is one of the most successful technical communities in India, which focus on Microsoft Technologies. We create exciting projects and share experience about Microsoft technology with passion."
organizerEmail: "info@k-mug.net"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://kmug.net/"

# Head
metaKeywords: "event, kmug, k-mug, devfest, microsoft, programming, windows, azure, developers, kerala, technical, community"
twitterAccount: "@k_mug"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/forms/4SSB3Jg94pYTPcjg1"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/slack/", text: "Slack"}
 - {permalink: "/blog/", text: "Blog"}
 - {link: "http://k-mug.eventbrite.com/", text: "Events"}
 - {permalink: "/team/", text: "Team"}
 - {link: "http://www.youtube.com/channel/UC-aE2GkdeltmzL4T9VfzTJg/live", text: "Live"}
 - {permalink: "/#footer", text: "Contact"}
bottomNavigationLinks:
 - {permalink: "/slack/", text: "Join K-MUG"}
rightNavigationButtons:
 - {permalink: "/slack/", text: "Join K-MUG"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "K-MUG <typeout>"
eventDate: "Year round events on everything technology!"
typeoutTextValues: '"", "Kochi", "Trivandrum", "Kozhikode"'
typeoutFallback: "Kochi"
heroButtons:
 - {permalink: "/slack/", text: "Join K-MUG"}
 - {link: "http://www.youtube.com/channel/UC-aE2GkdeltmzL4T9VfzTJg/live", text: "Attend Live"}

# About Block
aboutTitle: "About K-MUG"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Microsoft related event in the country carefully crafted for you by K-MUG! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Meetups", image: "meetups.jpg", text: "Half-day morning meetups! Want to network with some MVPs? Grab your cards and join our network!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "800", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "200", specialCharacter: "+", info: "hours", detail: "of K-MUG since 2006"}
 - {count: "40", specialCharacter: "+", info: "speakers", detail: "from Kerala and beyond"}
 - {count: "9", specialCharacter: "", info: "MVPs", detail: "Our valuable gems"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Orion India Systems, Meeting Hall"
eventLocationLink: "http://k-mug.net/logistics/"
eventStreetAddress: "103, Tejomaya"
eventAddressLocality: "Infopark, Kochi"
eventAddressLocalityRegion: "Kerala"
eventPostalCode: "682042"
eventAddressCountry: "India"
eventStartTime: "2016-06-23T08:00"
eventDoorTime: "09:00"
eventEndTime: "2016-12-30T18:00"
eventPlaceCoordinates: "10.010003, 76.365947"
mapCenterCoordinates: "10.010003, 76.365947"
mapMobileCenterCoordinates: "10.010003, 76.365947"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Athulya Auditorium"
venueFeatures: ["1 huge screen", "Good enough sound system", "Located directly in Infopark"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "KMUG"
twitterFeed: "http://k-mug.org/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "//k-mug.us14.list-manage.com/subscribe/post?u=796c687dbe93130ef8e89d3c0&amp;id=c3f7b3e004"
subscribeInfo: "We will announce more details about our events. Stay tuned!"

# Tickets Block
ticketsTitle: "Ticket Table"
ticketsInfo: "Tickets grant access to our meetup hall, coffee brakes, maybe-lunch and maybe-party. Accommodation is definitely NOT included in the ticket and come on we can't booze always."
ticketsOffers:
 -
  name: "UG Meeting Ticket"
  price: "0"
  priceCurrency: "Rs."
  ticketsNumber: "50"
  ribbon: "Click me!"
  featured: true
  buyButtonLink: "http://www.eventbrite.com/o/kerala-microsoft-users-group-101822805"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid ID at the security check in. Without ID at the check in, we might have to code it out to make you eligible for an entry."
  ticketContentList: ["Lot's of Technology know-how'", "Network with our MVPs", "Snacks (Coffeeee!!!)"]
  validFrom: "2016-06-01T00:00"
  validThrough: "2016-12-30T23:59"
  disabled: false
  soldOut: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/k_mug", icon: "twitter"}
 - {link: "https://facebook.com/TeamKmug/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://k-mug.org", text: "Kerala Microsoft Users Group"}
   - {link: "https://msdn.microsoft.com", text: "MSDN"}
   - {link: "https://technet.microsoft.com/", text: "Technet"}
   - {link: "https://mva.microsoft.com/", text: "Microsoft Virtual Academy"}
   - {link: "https://www.technicalcommunity.com", text: "Microsoft Technical Community"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:info@k-mug.net", text: "info@k-mug.net"}
   - {link: "tel:9645889033", text: "Call Praveen"}
   - {link: "tel:9746565890", text: "Call Anuraj"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "k-mug"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "K-MUG is one of the most successful technical community in India, which focus on Microsoft Technologies. Participation in K-MUG is an excellent, inexpensive way to receive technical content, education and to meet with peers to get more out of the Microsoft platforms, products, technologies, and resources. K-MUG is managed by the K-MUG Community Council (CC) , and more details about the CC be located here."


